import {expect,test} from '@playwright/test';
import {TestStepHelper} from '../helpers/test-step-helper';
import {resetEmulators} from '../helpers/reset-emulators';
test.beforeEach(resetEmulators);
test('US-009: Crystal Canopy keeps a solver-backed puzzle fixed to the ceiling',async({page},testInfo)=>{
  const tester=new TestStepHelper(page,testInfo);await page.goto('/');await page.getByLabel('Player name').fill('Cora');await page.getByRole('button',{name:'Continue'}).click();await expect(page.getByRole('button',{name:'Play anonymously'})).toBeEnabled({timeout:30000});await page.getByRole('button',{name:'Play anonymously'}).click();await expect(page.getByText('ANONYMOUS PLAYER READY')).toBeVisible({timeout:10000});await page.getByRole('button',{name:'Create a room'}).click();await expect(page).toHaveURL(/room\?code=TEST/,{timeout:10000});await page.getByRole('button',{name:/CRYSTAL CANOPY/}).click();await page.getByRole('button',{name:'Play',exact:true}).click();
  await expect(page.getByLabel('Crystal Canopy controller')).toBeVisible({timeout:10000});const board=page.getByLabel('Crystal Canopy board');await page.clock.pauseAt(Date.now());await page.locator('.tick').evaluate((element:HTMLElement)=>element.style.visibility='hidden');
  await tester.step('canopy-start',{description:'A low-level Crystal Canopy hangs twelve crystals from the cavern ceiling',networkStatus:'skip',verifications:[{spec:'Level zero contains twelve solver-backed crystals',check:async()=>{await expect(board).toHaveAttribute('data-remaining','12');await expect(board.locator('.occupied')).toHaveCount(12)}},{spec:'The ceiling-hung crystal treatment and launcher are visible',check:async()=>{await expect(board).toHaveClass(/canopy/);await expect(page.getByRole('button',{name:'Fire'})).toBeEnabled()}},{spec:'The controller fits the phone viewport',check:async()=>await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight)).toBe(true)}]});
  const plan=await page.evaluate(async()=>{const game=await(0,eval)("import('/src/lib/game/crystal-canopy.ts')") as typeof import('../../../src/lib/game/crystal-canopy');return game.solveCanopyPlan(game.generateCanopy(123456789,0))!});let cursor=2;
  for(const column of plan){while(cursor<column){await page.keyboard.press('ArrowRight');cursor++}while(cursor>column){await page.keyboard.press('ArrowLeft');cursor--}await page.keyboard.press('ArrowUp')}
  await expect(page.getByText('ROUND WIN')).toBeVisible({timeout:10000});await page.clock.pauseAt(Date.now());await page.locator('.command-status').evaluate((element:HTMLElement)=>element.style.visibility='hidden');
  await tester.step('canopy-clear',{description:'Tip shots clear the canopy without gravity or cascades',networkStatus:'skip',verifications:[{spec:'Exactly twelve direct shots empty the level-zero puzzle',check:async()=>await expect(board).toHaveAttribute('data-remaining','0')},{spec:'No Quarry cascade was generated',check:async()=>await expect(board).toHaveAttribute('data-cascades','0')},{spec:'The shared round lifecycle declares the clear',check:async()=>await expect(page.getByText('ROUND WIN')).toBeVisible()}]});tester.generateDocs();
});
