import{hasOnlyKeys,isInteger,isObject,isServerTime,isString,parseControllerEnvelope}from'./game.ts';
import type{StaxRecord,StaxTerminal}from'$lib/game/stax';
export interface StaxStartRecord{type:'game/started';ruleset:'stax';rulesVersion:'stax/1';seed:number;tickRate:60;round:number;matchId:string;previousGameId?:string;hostUid:string;roomId:string;audioOutput:'cast'|'controllers';players:Record<string,{seat:number;level:number}>;members:Record<string,true>;settings:{width:5;height:5;targetWins:3;matchRounds:3};scores:Record<string,number>}
export function parseStaxStart(value:unknown):StaxStartRecord{
 if(!isObject(value)||!hasOnlyKeys(value,['type','roomId','ruleset','rulesVersion','seed','tickRate','hostUid','audioOutput','members','players','settings','matchId','round','previousGameId','scores','serverTime'])||value.type!=='game/started'||value.ruleset!=='stax'||value.rulesVersion!=='stax/1'||value.tickRate!==60||!isInteger(value.seed,0,0xffffffff)||!isInteger(value.round,0,2)||!isString(value.matchId)||!isString(value.hostUid)||!isString(value.roomId)||!isServerTime(value.serverTime)||!isObject(value.members)||!isObject(value.players)||!isObject(value.scores)||!isObject(value.settings)||!hasOnlyKeys(value.settings,['width','height','targetWins','matchRounds'])||value.settings.width!==5||value.settings.height!==5||value.settings.targetWins!==3||value.settings.matchRounds!==3||(value.previousGameId!==undefined&&!isString(value.previousGameId))||(value.audioOutput!=='cast'&&value.audioOutput!=='controllers'))throw new Error('Invalid Stax start record.');
 const members=value.members as Record<string,unknown>,players=value.players as Record<string,unknown>,scores=value.scores as Record<string,unknown>,ids=Object.keys(players);
 if(ids.length<1||ids.length>4||!Object.entries(members).every(([id,included])=>isString(id)&&included===true)||!Object.entries(players).every(([id,player])=>isString(id)&&members[id]===true&&isObject(player)&&hasOnlyKeys(player,['seat','level'])&&isInteger(player.seat,0,3)&&isInteger(player.level,0,20))||!hasOnlyKeys(scores,ids)||!ids.every(id=>isInteger(scores[id],0,12)))throw new Error('Invalid Stax roster or scores.');
 return value as unknown as StaxStartRecord;
}
export function parseStaxTerminal(value:unknown):StaxTerminal&{stateHash:string;serverTime:unknown}{if(!isObject(value)||!hasOnlyKeys(value,['type','playerId','tick','result','score','misses','seat','stateHash','serverTime'])||value.type!=='player/terminal'||!isString(value.playerId)||!isInteger(value.tick,0)||!['cleared','lost'].includes(String(value.result))||!isInteger(value.score,0,1_000_000_000)||!isInteger(value.misses,0,5)||!isInteger(value.seat,0,3)||typeof value.stateHash!=='string'||!/^s1-[0-9a-f]{8}$/.test(value.stateHash)||!isServerTime(value.serverTime))throw new Error('Invalid Stax terminal record.');return value as unknown as StaxTerminal&{stateHash:string;serverTime:unknown}}
export function parseStaxRecord(commandId:string,value:unknown,pending=false):StaxRecord{const e=parseControllerEnvelope(commandId,value,pending),p=isObject(e.payload)?e.payload:{};if(e.type==='input/move'&&hasOnlyKeys(p,['dx'])&&(p.dx===-1||p.dx===1))return{commandId,...e,type:e.type,payload:{dx:p.dx}}as StaxRecord;if(['input/place','input/throw-back','input/accelerate-start','input/accelerate-end','input/restart'].includes(e.type)&&hasOnlyKeys(p,[]))return{commandId,...e,type:e.type,payload:{}}as StaxRecord;if(e.type==='progress/tick'&&hasOnlyKeys(p,['phase','stateHash'])&&['countdown','playing','cleared','lost'].includes(String(p.phase))&&typeof p.stateHash==='string'&&/^s1-[0-9a-f]{8}$/.test(p.stateHash))return{commandId,...e,type:e.type,payload:{phase:p.phase,stateHash:p.stateHash}}as StaxRecord;throw new Error('Invalid Stax controller payload.')}
