import{hasOnlyKeys,isInteger,isObject,isServerTime,isString,parseControllerEnvelope}from'./game.ts';import type{TetrisRecord}from'$lib/game/tetris';
export interface TetrisStartRecord{type:'game/started';ruleset:'tetris';rulesVersion:'tetris/1';seed:number;tickRate:60;round:number;matchId:string;previousGameId?:string;hostUid:string;roomId:string;audioOutput:'cast'|'controllers';players:Record<string,{seat:number}>;members:Record<string,true>;settings:{width:number;height:number;hiddenRows:number;matchRounds:number}}
export function parseTetrisStart(value:unknown):TetrisStartRecord{
 if(!isObject(value)||!hasOnlyKeys(value,['type','roomId','ruleset','rulesVersion','seed','tickRate','hostUid','audioOutput','members','players','settings','matchId','round','previousGameId','serverTime'])||value.type!=='game/started'||value.ruleset!=='tetris'||value.rulesVersion!=='tetris/1'||value.tickRate!==60||!isInteger(value.seed,0,0xffffffff)||!isInteger(value.round,0,99)||!isString(value.matchId)||!isString(value.hostUid)||!isString(value.roomId)||!isServerTime(value.serverTime)||!isObject(value.members)||!isObject(value.players)||!isObject(value.settings)||!hasOnlyKeys(value.settings,['width','height','hiddenRows','matchRounds'])||value.settings.width!==10||value.settings.height!==20||value.settings.hiddenRows!==2||!isInteger(value.settings.matchRounds,1,99)||(value.previousGameId!==undefined&&!isString(value.previousGameId))||(value.audioOutput!=='cast'&&value.audioOutput!=='controllers'))throw new Error('Invalid tetris/1 start record.');
 const members=value.members as Record<string,unknown>,players=value.players as Record<string,unknown>;if(!Object.entries(members).every(([id,included])=>isString(id)&&included===true)||!Object.entries(players).every(([id,player])=>isString(id)&&members[id]===true&&isObject(player)&&hasOnlyKeys(player,['seat'])&&isInteger(player.seat,0,3)))throw new Error('Invalid Tetris roster.');return value as unknown as TetrisStartRecord;
}
export function parseTetrisRecord(commandId:string,value:unknown,pending=false):TetrisRecord{
 const envelope=parseControllerEnvelope(commandId,value,pending),payload=isObject(envelope.payload)?envelope.payload:{};
 if(envelope.type==='input/move'&&hasOnlyKeys(payload,['dx'])&&(payload.dx===-1||payload.dx===1))return{commandId,...envelope,type:'input/move',payload:{dx:payload.dx}} as TetrisRecord;
 if(envelope.type==='input/rotate'&&hasOnlyKeys(payload,['direction'])&&(payload.direction==='clockwise'||payload.direction==='counterclockwise'))return{commandId,...envelope,type:'input/rotate',payload:{direction:payload.direction}} as TetrisRecord;
 if(['input/soft-drop-start','input/soft-drop-end','input/hard-drop'].includes(envelope.type)&&hasOnlyKeys(payload,[]))return{commandId,...envelope,type:envelope.type,payload:{}} as TetrisRecord;
 if(envelope.type==='progress/tick'&&hasOnlyKeys(payload,['phase','stateHash'])&&(payload.phase==='playing'||payload.phase==='lost')&&typeof payload.stateHash==='string'&&/^t1-[0-9a-f]{8}$/.test(payload.stateHash))return{commandId,...envelope,type:'progress/tick',payload:{phase:payload.phase,stateHash:payload.stateHash}} as TetrisRecord;
 throw new Error('Invalid Tetris controller payload.');
}
