<script lang="ts">
  import { onMount } from 'svelte';
  import PillController from '$lib/components/game/PillController.svelte';
  import TetrisController from '$lib/components/game/TetrisController.svelte';
  import MatchPuzzleController from '$lib/components/game/MatchPuzzleController.svelte';
  import StaxController from '$lib/components/game/StaxController.svelte';
  import LevelPicker from '$lib/components/game/LevelPicker.svelte';
  import { auth,firebaseConfigured } from '$lib/firebase/config';
  import { joinRoom,subscribeRoom,subscribeRoomPlayers,updatePlayerLevel } from '$lib/firebase/rooms';
  let code='',name='',roomId='',ruleset:'doctor'|'tetris'|'quarry'|'canopy'|'stax'|undefined,error='',needsName=false,loading=true,activeGameId='',selectedLevel=0;let stopRoom=()=>{},stopPlayers=()=>{};
  onMount(()=>{void initialize();return()=>{stopRoom();stopPlayers()}});
  async function initialize(){code=new URL(location.href).searchParams.get('code')?.toUpperCase()??'';if(!/^[A-Z]{4}$/.test(code)){error='A valid four-letter room code is required.';loading=false;return}if(!firebaseConfigured){error='Firebase configuration is required.';loading=false;return}name=localStorage.getItem('drm-player-name')??'';if(!name){needsName=true;loading=false;return}await resolve()}
  async function resolve(){loading=true;error='';try{const room=await joinRoom(code,name);roomId=room.id;ruleset=room.ruleset;activeGameId=room.activeGameId??'';stopRoom();stopPlayers();stopPlayers=subscribeRoomPlayers(room.id,players=>selectedLevel=players.find(player=>player.uid===auth?.currentUser?.uid)?.level??selectedLevel,cause=>error=cause.message);stopRoom=subscribeRoom(room.id,next=>{ruleset=next.ruleset;if(next.activeGameId)activeGameId=next.activeGameId},cause=>error=cause.message)} catch(cause){error=cause instanceof Error?cause.message:String(cause)}finally{loading=false}}
  async function save(){name=name.trim();if(!name||name.length>24){error='Player name must be between 1 and 24 characters.';return}localStorage.setItem('drm-player-name',name);needsName=false;await resolve()}
  async function chooseLevel(level:number){selectedLevel=level;try{await updatePlayerLevel(roomId,level)}catch(cause){error=cause instanceof Error?cause.message:String(cause)}}
</script>
{#if needsName}<main class="join"><form class="card" on:submit|preventDefault={save}><p class="eyebrow">Joining room {code}</p><h1>WHAT SHOULD PLAYERS CALL YOU?</h1><label>Player name<input aria-label="Player name" maxlength="24" autocomplete="nickname" bind:value={name}/></label><button>Join room</button></form>{#if error}<p role="alert">{error}</p>{/if}</main>{:else if error}<main class="join"><h1 role="alert">{error}</h1></main>{:else if loading}<main class="join"><p role="status">Loading controller…</p></main>{:else if !activeGameId}<main class="join"><p class="eyebrow">Joined room {code}</p><h1>WAITING FOR HOST</h1><p role="status">You are in. Choose your level while the host gets the game ready.</p><LevelPicker level={selectedLevel} change={chooseLevel}/><div class="guide">{#if ruleset==='quarry'||ruleset==='canopy'}<span>← → MOVE</span><span>↑ / A / B FIRE</span><span>L / R EDGE</span><span>R RESTART</span>{:else if ruleset==='stax'}<span>← → PADDLE</span><span>↓ / A PLACE</span><span>↑ / B THROW</span><span>SHIFT / L-R HURRY</span>{:else}<span>← → MOVE</span><span>↓ SOFT DROP</span><span>↑ HARD DROP</span><span>A / R ↻</span><span>B / T ↺</span>{/if}</div></main>{:else if ruleset==='tetris'}<TetrisController/>{:else if ruleset==='doctor'}<PillController/>{:else if ruleset==='quarry'}<MatchPuzzleController/>{:else if ruleset==='canopy'}<MatchPuzzleController variant="canopy"/>{:else if ruleset==='stax'}<StaxController/>{/if}
<style>.join{width:min(520px,calc(100% - 2rem));min-height:100vh;margin:0 auto;padding-top:5rem}.join form{display:grid;gap:1rem}.guide{display:flex;justify-content:center;flex-wrap:wrap;gap:.5rem;margin-top:1.5rem}.guide span{border:1px solid #3c3f50;padding:.45rem;color:var(--muted);font-size:.65rem}</style>
