<script lang="ts">
  import { onMount } from 'svelte';
  import PillController from '$lib/components/game/PillController.svelte';
  import TetrisController from '$lib/components/game/TetrisController.svelte';
  import { firebaseConfigured } from '$lib/firebase/config';
  import { joinRoom,subscribeRoom } from '$lib/firebase/rooms';
  let code='',name='',ruleset:'doctor'|'tetris'|undefined,error='',needsName=false,loading=true,activeGameId='';let stopRoom=()=>{};
  onMount(()=>{void initialize();return()=>stopRoom()});
  async function initialize(){code=new URL(location.href).searchParams.get('code')?.toUpperCase()??'';if(!/^[A-Z]{4}$/.test(code)){error='A valid four-letter room code is required.';loading=false;return}if(!firebaseConfigured){error='Firebase configuration is required.';loading=false;return}name=localStorage.getItem('drm-player-name')??'';if(!name){needsName=true;loading=false;return}await resolve()}
  async function resolve(){loading=true;error='';try{const room=await joinRoom(code,name);ruleset=room.ruleset;activeGameId=room.activeGameId??'';stopRoom();stopRoom=subscribeRoom(room.id,next=>{ruleset=next.ruleset;if(next.activeGameId)activeGameId=next.activeGameId},cause=>error=cause.message)} catch(cause){error=cause instanceof Error?cause.message:String(cause)}finally{loading=false}}
  async function save(){name=name.trim();if(!name||name.length>24){error='Player name must be between 1 and 24 characters.';return}localStorage.setItem('drm-player-name',name);needsName=false;await resolve()}
</script>
{#if needsName}<main class="join"><form class="card" on:submit|preventDefault={save}><p class="eyebrow">Joining room {code}</p><h1>WHAT SHOULD PLAYERS CALL YOU?</h1><label>Player name<input aria-label="Player name" maxlength="24" autocomplete="nickname" bind:value={name}/></label><button>Join room</button></form>{#if error}<p role="alert">{error}</p>{/if}</main>{:else if error}<main class="join"><h1 role="alert">{error}</h1></main>{:else if loading}<main class="join"><p role="status">Loading controller…</p></main>{:else if !activeGameId}<main class="join"><p class="eyebrow">Joined room {code}</p><h1>WAITING FOR HOST</h1><p role="status">You are in. Keep this screen open; controls appear when the host starts the game.</p><div class="guide"><span>← → MOVE</span><span>↓ SOFT DROP</span><span>↑ HARD DROP</span><span>A / R ↻</span><span>B / T ↺</span></div></main>{:else if ruleset==='tetris'}<TetrisController/>{:else if ruleset==='doctor'}<PillController/>{/if}
<style>.join{width:min(520px,calc(100% - 2rem));min-height:100vh;margin:0 auto;padding-top:5rem}.join form{display:grid;gap:1rem}.guide{display:flex;justify-content:center;flex-wrap:wrap;gap:.5rem;margin-top:1.5rem}.guide span{border:1px solid #3c3f50;padding:.45rem;color:var(--muted);font-size:.65rem}</style>
