<script lang="ts">
 import{onMount}from'svelte';import{Canvas,T}from'@threlte/core';import{OrbitControls}from'@threlte/extras';import StaxPaddle from'./StaxPaddle.svelte';import StaxTile from'./StaxTile.svelte';import{staxLevelRules,type StaxColor,type StaxState}from'$lib/game/stax';import{STAX_PRESENTATION_TICKS}from'$lib/presentation/stax';
 export let state:StaxState;export let compact=false;export let label='Stax ramp';export let selectLane:((lane:number)=>void)|undefined=undefined;export let onChainCue:(()=>void)|undefined=undefined;export let onTerminalPresentationComplete:(()=>void)|undefined=undefined;
 let inspect=false;
 const x=(lane:number)=>(lane-2)*1.15;
 const rampAngle=.13,rampCenterY=.72,rampCenterZ=-.52,rampHalfThickness=.09;
 const farZ=-4.35,nearZ=3.55,paddleZ=4.08,catchY=.2,stackStep=.42,binY=-1.78,binZ=5.35,binPlatformY=-2.25;
 $: travel=staxLevelRules(state.level).travel;
 const rampSurface=(z:number)=>rampCenterY+rampHalfThickness/Math.cos(rampAngle)-(z-rampCenterZ)*Math.tan(rampAngle);
 const route=(progress:number,returning=false)=>{const t=Math.min(1,progress/(returning?360:travel)),towardPlayer=returning?1-t:t,z=farZ+towardPlayer*(nearZ-farZ),roll=(returning?-1:1)*progress*.06+rampAngle,clearance=.21*Math.abs(Math.cos(roll))+.47*Math.abs(Math.sin(roll));return{z,y:rampSurface(z)+clearance+.015,roll}};
 type Visual={id:number;color:StaxColor;kind:'catch'|'miss'|'place';lane:number;column?:number;row?:number;startedTick:number;durationTicks:number;roll:number};
 type Resolution={startedTick:number;column:number;placedRow:number;waves:StaxState['lastClearWaves'];cued:number};
 type BoardTile={key:string;color:StaxColor;column:number;y:number;scale:number;glow:number};
 const{place:PLACE_TICKS,settle:SETTLE_TICKS,burst:BURST_TICKS,fall:FALL_TICKS}=STAX_PRESENTATION_TICKS;
 let visuals:Visual[]=[],resolution:Resolution|undefined,renderedBoardTiles:BoardTile[]=[],renderedResolutionPhase='',animatedPlacement=-1,animatedResolutionPlacement=-1,displayTick=0,lastStateTick=0,seen=false,terminalPresentationComplete=true,presentationFrame=0,lastPresentationTime=0,previousRamp=new Map<number,{color:StaxColor;lane:number;returning?:boolean}>(),previousPaddle:Array<{id:number;color:StaxColor}>=[],previousCounts:number[]=[],previousPlacements=0;
 const normalRoll=(roll:number)=>Math.atan2(Math.sin(roll),Math.cos(roll));
 const nextHorizontalRoll=(roll:number)=>roll+((Math.PI-((roll%Math.PI)+Math.PI)%Math.PI)%Math.PI);
 const snapshot=()=>{previousRamp=new Map(state.ramp.map(tile=>[tile.id,{color:tile.color,lane:tile.lane,returning:tile.returning}]));previousPaddle=state.paddle.map(tile=>({...tile}));previousCounts=state.columns.map(column=>column.length);previousPlacements=state.placements};
 const advancePresentation=()=>{visuals=visuals.filter(visual=>displayTick-visual.startedTick<visual.durationTicks);if(resolution){const elapsed=displayTick-resolution.startedTick,total=PLACE_TICKS+SETTLE_TICKS+resolution.waves.length*(BURST_TICKS+FALL_TICKS);if(elapsed>=total)resolution=undefined;else{const wave=Math.floor(Math.max(0,elapsed-PLACE_TICKS-SETTLE_TICKS)/(BURST_TICKS+FALL_TICKS));if(elapsed>=PLACE_TICKS+SETTLE_TICKS&&wave<resolution.waves.length&&wave>=resolution.cued){onChainCue?.();resolution.cued=wave+1}}}};
 const terminal=()=>state.phase==='cleared'||state.phase==='lost';
 const animateTerminal=(now:number)=>{if(!terminal()||(!visuals.length&&!resolution)){const notify=!terminalPresentationComplete&&terminal();terminalPresentationComplete=true;presentationFrame=0;lastPresentationTime=0;if(notify)onTerminalPresentationComplete?.();return}if(lastPresentationTime)displayTick+=Math.min(3,(now-lastPresentationTime)/(1000/60));lastPresentationTime=now;advancePresentation();presentationFrame=requestAnimationFrame(animateTerminal)};
 const continueTerminalPresentation=()=>{terminalPresentationComplete=false;if(!presentationFrame){lastPresentationTime=0;presentationFrame=requestAnimationFrame(animateTerminal)}};
 onMount(()=>()=>cancelAnimationFrame(presentationFrame));
 function observe(){
  if(!seen||state.phase==='countdown'){const recoveredTerminal=!seen&&terminal();visuals=[];resolution=undefined;animatedPlacement=-1;animatedResolutionPlacement=-1;displayTick=state.tick;lastStateTick=state.tick;seen=true;terminalPresentationComplete=true;snapshot();if(recoveredTerminal)queueMicrotask(()=>onTerminalPresentationComplete?.());return}
  displayTick+=Math.min(1,Math.max(0,state.tick-lastStateTick));lastStateTick=state.tick;
  advancePresentation();const paddleIds=new Set(state.paddle.map(tile=>tile.id));
  for(const[id,tile]of previousRamp)if(!state.ramp.some(current=>current.id===id))visuals=[...visuals,{id,color:tile.color,kind:paddleIds.has(id)?'catch':'miss',lane:tile.lane,startedTick:displayTick,durationTicks:paddleIds.has(id)?25:54,roll:normalRoll(route(tile.returning?360:travel,tile.returning).roll)}];
  const placement=state.lastPlacement,freshPlacement=Boolean(placement&&placement.placement!==animatedPlacement);
  const freshResolution=state.lastClearWaves.length&&state.placements!==animatedResolutionPlacement;
  if(freshPlacement&&placement){visuals=[...visuals.filter(visual=>visual.id!==placement.id),{id:placement.id,color:placement.color,kind:'place',lane:placement.column,column:placement.column,row:placement.row,startedTick:displayTick,durationTicks:PLACE_TICKS,roll:0}];animatedPlacement=placement.placement}
  if(freshResolution&&placement){resolution={startedTick:displayTick,column:placement.column,placedRow:placement.row,waves:structuredClone(state.lastClearWaves),cued:0};animatedResolutionPlacement=state.placements}
  if(terminal()&&(visuals.length||resolution))continueTerminalPresentation();else if(!terminal())terminalPresentationComplete=true;
  snapshot();
 }
 $: state,observe();
 const activeVisual=(kind:Visual['kind'],id:number)=>visuals.some(visual=>visual.kind===kind&&visual.id===id);
 const restingPaddleY=(count:number)=>count?catchY-.35-(count-1)*stackStep:catchY;
 const paddleY=()=>{const landing=visuals.find(visual=>visual.kind==='catch');if(!landing)return restingPaddleY(state.paddle.length);const t=Math.max(0,Math.min(1,(displayTick-landing.startedTick)/landing.durationTicks)),push=Math.max(0,(t-.5)/.5);return restingPaddleY(Math.max(0,state.paddle.length-1))+(restingPaddleY(state.paddle.length)-restingPaddleY(Math.max(0,state.paddle.length-1)))*(1-Math.pow(1-push,3))};
 const boardTiles=():BoardTile[]=>{if(!resolution){const moving=visuals.find(visual=>visual.kind==='place');return state.columns.flatMap((column,c)=>column.flatMap((color,r)=>moving?.column===c&&moving.row===r?[]:[{key:`rest-${c}-${r}`,color,column:c,y:binY+r*stackStep,scale:1,glow:.28}]))}const elapsed=displayTick-resolution.startedTick;if(elapsed<PLACE_TICKS+SETTLE_TICKS){const board=resolution.waves[0].before;return board.flatMap((column,c)=>column.map((color,r)=>({key:`form-${c}-${r}`,color,column:c,y:binY+r*stackStep,scale:c===resolution?.column&&r===resolution.placedRow&&elapsed<PLACE_TICKS?0:1,glow:.28})))}const waveTime=elapsed-PLACE_TICKS-SETTLE_TICKS,waveIndex=Math.min(resolution.waves.length-1,Math.floor(waveTime/(BURST_TICKS+FALL_TICKS))),phase=waveTime%(BURST_TICKS+FALL_TICKS),wave=resolution.waves[waveIndex],cleared=new Set(wave.cells.map(cell=>`${cell.column}:${cell.row}`));if(phase<BURST_TICKS){const p=phase/BURST_TICKS,pulse=1+.18*Math.sin(Math.PI*Math.min(1,p*2)),vanish=p<.55?pulse:Math.max(.05,1-(p-.55)/.45);return wave.before.flatMap((column,c)=>column.map((color,r)=>({key:`burst-${waveIndex}-${c}-${r}`,color,column:c,y:binY+r*stackStep,scale:cleared.has(`${c}:${r}`)?vanish:1,glow:cleared.has(`${c}:${r}`)?1:.28})))}const p=(phase-BURST_TICKS)/FALL_TICKS,ease=p*p*(3-2*p),tiles:BoardTile[]=[];for(let c=0;c<5;c++){let destination=0;for(let r=0;r<wave.before[c].length;r++){if(cleared.has(`${c}:${r}`))continue;tiles.push({key:`fall-${waveIndex}-${c}-${r}`,color:wave.before[c][r],column:c,y:binY+(r+(destination-r)*ease)*stackStep,scale:1,glow:.28});destination++}}return tiles};
 $: state,visuals,resolution,displayTick,renderedBoardTiles=boardTiles();
 const resolutionPhase=()=>{if(!resolution)return'';const elapsed=displayTick-resolution.startedTick;if(elapsed<PLACE_TICKS)return'placing';if(elapsed<PLACE_TICKS+SETTLE_TICKS)return'settled';return(elapsed-PLACE_TICKS-SETTLE_TICKS)%(BURST_TICKS+FALL_TICKS)<BURST_TICKS?'burst':'fall'};
 $: state,resolution,displayTick,renderedResolutionPhase=resolutionPhase();
 const visualPose=(visual:Visual)=>{const t=Math.max(0,Math.min(1,(displayTick-visual.startedTick)/visual.durationTicks)),ease=1-Math.pow(1-t,3);if(visual.kind==='miss'){const start=route(travel);return{position:[x(visual.lane),start.y-4.8*t*t,start.z+2.8*t]as[number,number,number],rotation:[visual.roll+8*t,0,.7*t]as[number,number,number]}}if(visual.kind==='catch'){const start=route(travel),y=start.y+(catchY-start.y)*ease+.16*Math.sin(Math.PI*t),endRoll=nextHorizontalRoll(visual.roll);return{position:[x(visual.lane),y,start.z+(paddleZ-start.z)*ease]as[number,number,number],rotation:[visual.roll+(endRoll-visual.roll)*ease,0,0]as[number,number,number]}}const flipEnd=.46,column=visual.column??visual.lane,row=visual.row??0;if(t<flipEnd){const p=t/flipEnd;return{position:[x(visual.lane)+(x(column)-x(visual.lane))*p,catchY+.2*Math.sin(Math.PI*p),paddleZ+(binZ-paddleZ)*p]as[number,number,number],rotation:[Math.PI*p,0,0]as[number,number,number]}}const fall=(t-flipEnd)/(1-flipEnd),drop=fall*fall;return{position:[x(column),catchY+(binY+row*stackStep-catchY)*drop,binZ]as[number,number,number],rotation:[Math.PI,0,0]as[number,number,number]}};
</script>
<div class="scene" class:compact aria-label={label} data-tick={state.tick} data-phase={state.phase} data-resolution-phase={renderedResolutionPhase} data-terminal-presentation={terminalPresentationComplete?'complete':'playing'} data-paddle-lane={state.paddleLane} data-paddle-count={state.paddle.length} data-paddle-y={paddleY()} data-ramp-count={state.ramp.length} data-leading-lane={state.ramp[0]?.lane??''} data-leading-color={state.ramp[0]?.color??''} data-leading-progress={state.ramp[0]?.progress??''} data-leading-roll={state.ramp[0]?route(state.ramp[0].progress,state.ramp[0].returning).roll:''} data-column-counts={state.columns.map(column=>column.length).join(',')} data-rendered-board-count={renderedBoardTiles.length} data-misses={state.misses} data-visual-transitions={visuals.map(visual=>visual.kind).join(',')} data-visual-progress={visuals[0]?Math.floor(displayTick-visuals[0].startedTick):''} data-score={state.score} data-ramp-direction="far-to-player" data-roll-direction="edge-over-edge-toward-player" data-paddle-position="player-edge" data-bin-position="below-paddle" data-bin-layout="vertical-stacks">
 <Canvas dpr={[1,2]}>
  {#key inspect}<T.PerspectiveCamera makeDefault position={[0,6.1,12.4]} rotation={[-.58,0,0]} fov={43}/>{/key}{#if selectLane&&inspect}<OrbitControls enableDamping target={[0,-.35,.7]}/>{/if}
  <T.Color attach="background" args={['#05050a']}/><T.AmbientLight intensity={.72}/><T.DirectionalLight position={[5,10,7]} intensity={4} color="#fff0dd" castShadow/><T.DirectionalLight position={[-8,5,-5]} intensity={3} color="#cceeff"/><T.SpotLight position={[0,8,-5]} intensity={10} color="#00ffcc" angle={.5} penumbra={.5} decay={0} distance={20}/>
  <T.Mesh rotation={[.13,0,0]} position={[0,.72,-.52]} receiveShadow><T.BoxGeometry args={[6.3,.18,8.35]}/><T.MeshStandardMaterial color="#11182b" metalness={.28} roughness={.38}/></T.Mesh>
  {#each Array(6) as _,i}<T.Mesh rotation={[.13,0,0]} position={[(i-2.5)*1.15,.83,-.52]}><T.BoxGeometry args={[.035,.035,8.2]}/><T.MeshBasicMaterial color="#2c4777"/></T.Mesh>{/each}
  {#each state.ramp as tile(tile.id)}{@const p=route(tile.progress,tile.returning)}<StaxTile color={tile.color} position={[x(tile.lane),p.y,p.z]} rotation={[p.roll,0,0]}/>{/each}
  <T.Mesh position={[0,binPlatformY,5.35]} receiveShadow><T.BoxGeometry args={[6.3,.18,1.45]}/><T.MeshStandardMaterial color="#0b1020" metalness={.22} roughness={.42}/></T.Mesh>
  {#each Array(6) as _,i}<T.Mesh position={[(i-2.5)*1.15,binPlatformY+.105,5.35]}><T.BoxGeometry args={[.025,.025,1.32]}/><T.MeshBasicMaterial color="#263d68"/></T.Mesh>{/each}
  <T.Mesh position={[0,binPlatformY+.105,4.68]}><T.BoxGeometry args={[5.75,.025,.035]}/><T.MeshBasicMaterial color="#263d68"/></T.Mesh><T.Mesh position={[0,binPlatformY+.105,6.02]}><T.BoxGeometry args={[5.75,.025,.035]}/><T.MeshBasicMaterial color="#263d68"/></T.Mesh>
  {#each renderedBoardTiles as tile(tile.key)}{#if tile.scale>0}<StaxTile color={tile.color} position={[x(tile.column),tile.y,binZ]} scale={tile.scale} glow={tile.glow}/>{/if}{/each}
  <StaxPaddle position={[x(state.paddleLane),paddleY(),paddleZ]}/>
  {#each state.paddle as held,i}{#if !activeVisual('catch',held.id)}<StaxTile color={held.color} position={[x(state.paddleLane),catchY-(state.paddle.length-1-i)*stackStep,paddleZ]}/>{/if}{/each}
  {#each visuals as visual(visual.kind+visual.id)}{@const pose=visualPose(visual)}<StaxTile color={visual.color} position={pose.position} rotation={pose.rotation}/>{/each}
 </Canvas>
 {#if selectLane&&!inspect}<div class="lanes">{#each Array(5) as _,lane}<button aria-label={`Catch lane ${lane+1}`} on:pointerdown|preventDefault={()=>selectLane?.(lane)}></button>{/each}</div>{/if}{#if selectLane}<button class="inspect" class:active={inspect} aria-label={inspect?'Exit orbit view':'Inspect scene in orbit view'} aria-pressed={inspect} on:click={()=>inspect=!inspect}>{inspect?'EXIT ORBIT':'ORBIT VIEW'}</button>{/if}{#if state.phase==='countdown'}<strong class="countdown">{Math.max(1,Math.ceil(state.countdown/60))}</strong>{/if}
</div>
<style>.scene{position:relative;width:min(92vw,72dvh);aspect-ratio:4/5;overflow:hidden;border:1px solid #253150;border-radius:1rem;box-shadow:0 0 40px #00c8ff18}.countdown{position:absolute;inset:50% auto auto 50%;transform:translate(-50%,-50%);font:900 5rem/1 'Arial Black';color:#fff;text-shadow:0 0 25px #55ddff}.scene.compact{width:min(24vw,34dvh)}.lanes{position:absolute;inset:0;display:grid;grid-template-columns:repeat(5,1fr)}.lanes button{border:0;background:transparent;box-shadow:none;padding:0}.lanes button:hover{background:#55ddff12;transform:none}.inspect{position:absolute;z-index:4;right:.45rem;top:.45rem;padding:.35rem .45rem;font-size:.48rem;background:#080b12cc;color:#70eeff;border:1px solid #315979;box-shadow:none}.inspect:hover,.inspect.active{transform:none;background:#12344add}@media(max-width:700px){.scene{width:min(96vw,67dvh)}} </style>
