import {doc,serverTimestamp as firestoreTimestamp,updateDoc} from 'firebase/firestore';
import {get,onChildAdded,onDisconnect,onValue,push,ref,runTransaction,serverTimestamp,set,type Unsubscribe} from 'firebase/database';
import {auth,firestore,realtimeDatabase} from './config';import type{RoomPlayer}from'./rooms';
import {advanceTetris,applyTetrisInput,createTetris,hashTetris,replayTetris,TETRIS_RULES,type TetrisInput,type TetrisRecord,type TetrisState}from'$lib/game/tetris';
import type{PillMatchLifecycle}from'$lib/game/pill-bottle';
import{FixedTickClock}from'$lib/runtime/fixed-tick-clock';
import{startRealtimeGame}from'$lib/runtime/start-game';
import{ReplayObserver}from'$lib/runtime/replay-observer';
import{controllerStorageKey,loadStoredArray,saveStoredArray}from'$lib/runtime/local-store';
import{deriveMatchLifecycle}from'$lib/runtime/lifecycle';

export interface TetrisStart{seed:number;round:number;hostUid:string;roomId:string;audioOutput:'cast'|'controllers';players:Record<string,{seat:number}>;members:Record<string,true>;settings:{matchRounds:number}}
export interface TetrisControllerState{playerId?:string;tick:number;ready:boolean;state?:TetrisState;lifecycle?:PillMatchLifecycle;audioOutput?:'cast'|'controllers';error?:string;lastCommand?:string}
export interface TetrisProgress{playerId:string;tick:number;controllerTick?:number;lag?:number;state:TetrisState;hashMatches:boolean}
function parseStart(value:any):TetrisStart{if(!value||value.rulesVersion!=='tetris/1'||value.ruleset!=='tetris'||!value.players)throw new Error('Invalid Tetris start record.');return value}
function parseRecord(id:string,value:any):TetrisRecord{if(!value||value.playerId===undefined||!Number.isInteger(value.tick)||!Number.isInteger(value.clientSeq)||!['input/move','input/rotate','input/soft-drop-start','input/soft-drop-end','input/hard-drop','progress/tick'].includes(value.type))throw new Error('Invalid Tetris record.');return{commandId:id,...value}}
export async function startTetrisGame(roomId:string,members:RoomPlayer[],hostMode:'player'|'display'){
 return startRealtimeGame({ruleset:'tetris',rulesVersion:'tetris/1',tickRate:TETRIS_RULES.tickRate,settings:{width:10,height:20,hiddenRows:2,matchRounds:1}},roomId,members,hostMode);
}
export function subscribeTetrisLifecycle(gameId:string,receive:(value:PillMatchLifecycle)=>void,fail:(e:Error)=>void){if(!realtimeDatabase)throw new Error('Firebase unavailable.');let ids:string[]=[],matchRounds=1,round=0;let terminals:Array<{playerId:string;result:'lost';tick:number}>=[];const publish=()=>{if(ids.length)receive(deriveMatchLifecycle(ids,terminals,[],round,matchRounds))};const stops:Unsubscribe[]=[];void get(ref(realtimeDatabase,`games/${gameId}/start`)).then(s=>{const start=parseStart(s.val());ids=Object.keys(start.players);matchRounds=start.settings.matchRounds;round=start.round;stops.push(onChildAdded(ref(realtimeDatabase!,`games/${gameId}/terminals`),snap=>{const v=snap.val();if(v?.result==='lost')terminals=[...terminals.filter(t=>t.playerId!==v.playerId),{playerId:v.playerId,result:'lost',tick:v.tick}];publish()},fail));publish()}).catch(e=>fail(e instanceof Error?e:new Error(String(e))));return()=>stops.forEach(stop=>stop())}
export function createTetrisController(gameId:string,receive:(state:TetrisControllerState)=>void){if(!auth?.currentUser||!realtimeDatabase)throw new Error('Firebase unavailable.');const playerId=auth.currentUser.uid,epochId=crypto.randomUUID(),clock=new FixedTickClock(TETRIS_RULES.tickRate),storageKey=controllerStorageKey('tetris',gameId,playerId,'outbox');let state:TetrisState|undefined,tick=0,seq=0,ready=false,destroyed=false,frame=0,lastProgress=-1,lastCommand:string|undefined,audioOutput:'cast'|'controllers'|undefined,lifecycle:PillMatchLifecycle|undefined,flushing=false,retry:ReturnType<typeof setTimeout>|undefined;let outbox=loadStoredArray(localStorage,storageKey,value=>{if(!value||typeof value!=='object'||typeof(value as{commandId?:unknown}).commandId!=='string')throw new Error('Invalid Tetris outbox.');const{commandId,...record}=value as TetrisRecord;return parseRecord(commandId,record)});const publish=(error?:string)=>receive({playerId,tick,ready,state:state?structuredClone(state):undefined,lifecycle,audioOutput,error,lastCommand});const stopLife=subscribeTetrisLifecycle(gameId,next=>{lifecycle=next;if(next.finished)cancelAnimationFrame(frame);publish()},e=>publish(e.message));
 const saveOutbox=()=>saveStoredArray(localStorage,storageKey,outbox);
 async function flush(){if(flushing||!ready||destroyed||!realtimeDatabase||!outbox.length)return;flushing=true;try{while(outbox.length){const record=[...outbox].sort((a,b)=>a.clientSeq-b.clientSeq)[0],{commandId,...data}=record;await set(ref(realtimeDatabase,`games/${gameId}/players/${playerId}/records/${commandId}`),{...data,serverTime:serverTimestamp()});outbox=outbox.filter(item=>item.commandId!==commandId);saveOutbox()}}catch(e){publish(e instanceof Error?e.message:String(e));retry=setTimeout(()=>{retry=undefined;void flush()},1000)}finally{flushing=false}}
 const write=(input:TetrisInput|{type:'progress/tick';payload:{phase:'playing'|'lost';stateHash:string}})=>{const item=push(ref(realtimeDatabase!,`games/${gameId}/players/${playerId}/records`));const record={commandId:item.key!,playerId,epochId,clientSeq:++seq,tick,...input}as TetrisRecord;outbox=[...outbox,record].sort((a,b)=>a.clientSeq-b.clientSeq);saveOutbox();void flush();return record};
 const progress=(force=false)=>{if(!state||(!force&&tick-lastProgress<15))return;write({type:'progress/tick',payload:{phase:state.phase,stateHash:hashTetris(state)}});lastProgress=tick};
 const isLost=()=>state?.phase==='lost';const terminal=()=>{if(isLost()&&state)void set(ref(realtimeDatabase!,`games/${gameId}/terminals/${playerId}`),{type:'player/terminal',playerId,tick,result:'lost',stateHash:hashTetris(state),serverTime:serverTimestamp()}).catch(e=>publish(e.message))};
 const loop=(now:number)=>{if(destroyed||!ready||!state||isLost()||lifecycle?.finished)return;for(let ticks=clock.consume(now);ticks>0;ticks--){advanceTetris(state);tick=state.tick}progress();if(isLost()){progress(true);terminal()}publish();frame=requestAnimationFrame(loop)};
 const stopStart=onValue(ref(realtimeDatabase,`games/${gameId}/start`),async snap=>{if(ready)return;try{const start=parseStart(snap.val());if(!start.players[playerId])throw new Error('Player is not part of this Tetris game.');audioOutput=start.audioOutput;const writer=ref(realtimeDatabase!,`games/${gameId}/players/${playerId}/writer`);const claim=await runTransaction(writer,current=>current===null?{epochId,clientId:crypto.randomUUID()}:undefined,{applyLocally:false});if(!claim.committed)throw new Error('This controller is already active in another tab.');await onDisconnect(writer).remove();const history=await get(ref(realtimeDatabase!,`games/${gameId}/players/${playerId}/records`)),byId=new Map<string,TetrisRecord>();history.forEach(child=>{const record=parseRecord(child.key!,child.val());byId.set(record.commandId,record)});for(const record of outbox)byId.set(record.commandId,record);const records=[...byId.values()].sort((a,b)=>a.clientSeq-b.clientSeq);state=replayTetris(createTetris(start.seed),Math.max(0,...records.map(r=>r.tick)),records);tick=state.tick;seq=Math.max(0,...records.map(r=>r.clientSeq));await set(ref(realtimeDatabase!,`games/${gameId}/players/${playerId}/epochs/${epochId}`),{clientId:crypto.randomUUID(),startedFromTick:tick,startedFromCommandSeq:seq,serverTime:serverTimestamp()});ready=true;void flush();progress(true);publish();frame=requestAnimationFrame(loop);return}catch(e){publish(e instanceof Error?e.message:String(e));return}},e=>publish(e.message));
 const online=()=>void flush();window.addEventListener('online',online);
 return{command(input:TetrisInput){if(!ready||!state||state.phase!=='playing')return;write(input);applyTetrisInput(state,input);tick=state.tick;lastCommand=`${input.type} · tick ${tick}`;if(isLost()){progress(true);terminal()}publish()},destroy(){progress(true);destroyed=true;stopStart();stopLife();cancelAnimationFrame(frame);window.removeEventListener('online',online);if(retry)clearTimeout(retry)}};
}
export function subscribeTetrisProgress(gameId:string,receive:(p:TetrisProgress[])=>void,fail:(e:Error)=>void){
 if(!realtimeDatabase)throw new Error('Firebase unavailable.');let destroyed=false,frame=0,start:TetrisStart|undefined;
 const clock=new FixedTickClock(TETRIS_RULES.tickRate),histories=new Map<string,TetrisRecord[]>(),observers=new Map<string,ReplayObserver<TetrisState,TetrisRecord>>(),stops:Unsubscribe[]=[];
 const adapter={clone:(state:TetrisState)=>structuredClone(state),tick:(state:TetrisState)=>state.tick,
  advanceTo:(state:TetrisState,target:number)=>{while(state.tick<target&&state.phase==='playing')advanceTetris(state)},
  apply:(state:TetrisState,record:TetrisRecord)=>{if(record.type!=='progress/tick')applyTetrisInput(state,record)},hash:hashTetris,phase:(state:TetrisState)=>state.phase,
  progress:(record:TetrisRecord)=>record.type==='progress/tick'?record.payload:undefined};
 const publish=()=>receive([...observers].map(([playerId,observer])=>{const snapshot=observer.snapshot();return{playerId,tick:snapshot.displayTick,controllerTick:snapshot.controllerTick,lag:snapshot.lag,state:snapshot.state,hashMatches:snapshot.hashMatches}}));
 void get(ref(realtimeDatabase,`games/${gameId}/start`)).then(async snap=>{start=parseStart(snap.val());let initialDisplayTick=0;
  await Promise.all(Object.keys(start.players).map(async id=>{const history=await get(ref(realtimeDatabase!,`games/${gameId}/players/${id}/records`)),records:TetrisRecord[]=[];history.forEach(child=>{records.push(parseRecord(child.key!,child.val()))});records.sort((a,b)=>a.clientSeq-b.clientSeq);histories.set(id,records);for(const record of records)if(record.type==='progress/tick')initialDisplayTick=Math.max(initialDisplayTick,record.tick)}));
  if(destroyed)return;for(const id of Object.keys(start.players)){const observer=new ReplayObserver(adapter,createTetris(start.seed),initialDisplayTick);observers.set(id,observer);for(const record of histories.get(id)??[])observer.receive(record);stops.push(onChildAdded(ref(realtimeDatabase!,`games/${gameId}/players/${id}/records`),child=>{try{observer.receive(parseRecord(child.key!,child.val()));publish()}catch(e){fail(e instanceof Error?e:new Error(String(e)))}},fail))}
  const loop=(now:number)=>{if(destroyed)return;for(let ticks=clock.consume(now);ticks>0;ticks--)for(const observer of observers.values())observer.advance();publish();frame=requestAnimationFrame(loop)};publish();frame=requestAnimationFrame(loop)
 }).catch(e=>fail(e instanceof Error?e:new Error(String(e))));return()=>{destroyed=true;cancelAnimationFrame(frame);stops.forEach(stop=>stop())}
}
