<script lang="ts">
  import type{QuarryState}from'$lib/game/quarry-match';
  export let state:QuarryState;export let label='Quarry Match board';export let compact=false;
  const mark:Record<string,string>={cyan:'◆',pink:'●',yellow:'✦',green:'▲',purple:'■'};
</script>
<div class="quarry-shell" class:compact aria-label={label} data-remaining={60-state.removed} data-cursor={state.cursor}>
  <div class="progress" aria-label="Current match group">{#each [0,1,2] as slot}<span class:filled={slot<state.groupCount} class:cyan={state.groupColor==='cyan'} class:pink={state.groupColor==='pink'} class:yellow={state.groupColor==='yellow'} class:green={state.groupColor==='green'} class:purple={state.groupColor==='purple'}>{slot<state.groupCount&&state.groupColor?mark[state.groupColor]:'·'}</span>{/each}</div>
  <div class="board">{#each state.columns as column,col}{#each Array(12) as _,visualRow}{@const color=column[11-visualRow]}<div class="cell" class:occupied={Boolean(color)} class:cyan={color==='cyan'} class:pink={color==='pink'} class:yellow={color==='yellow'} class:green={color==='green'} class:purple={color==='purple'}>{color?mark[color]:''}</div>{/each}<div class="cursor" class:selected={state.cursor===col}>▲</div>{/each}</div>
</div>
<style>
  .quarry-shell{width:min(72vw,52dvh,430px);display:grid;gap:.35rem}.progress{display:flex;justify-content:center;gap:.35rem}.progress span{display:grid;place-items:center;width:1.7em;aspect-ratio:1;border:1px solid #45495b;color:var(--muted);background:#11131b}.progress .filled{color:#08090d;border-color:white}.board{display:grid;grid-template-columns:repeat(5,1fr);grid-template-rows:repeat(13,1fr);grid-auto-flow:column;gap:2px;padding:.45rem;background:linear-gradient(#161925,#0d0f16);border:3px solid #3f4355;box-shadow:7px 7px 0 #08090d;aspect-ratio:5/12.7}.cell{display:grid;place-items:center;border-radius:22%;font-size:clamp(.55rem,2.4dvh,1.15rem);color:#090a0e;text-shadow:0 1px #ffffff66}.occupied{box-shadow:inset 0 3px #ffffff55,inset 0 -4px #00000035,0 1px 2px #000}.cyan{background:#30d9d4}.pink{background:#ff4f91}.yellow{background:#f5d547}.green{background:#65d75c}.purple{background:#aa79ff}.cursor{display:grid;place-items:center;color:#4b4e5d;font-size:clamp(.5rem,2dvh,1rem)}.cursor.selected{color:var(--yellow);filter:drop-shadow(0 0 4px var(--yellow))}.compact{width:100%;gap:.1rem}.compact .board{border-width:1px;padding:.15rem;gap:1px;box-shadow:2px 2px 0 #08090d}.compact .progress{gap:1px;font-size:.35rem}.compact .progress span{width:1.2em}.compact .cell{font-size:.35rem}
</style>
